import { ConferenceData } from '@/types/conference';

export const DEFAULT_CONFERENCE_DATA: ConferenceData = {
  id: 'michigan-ai-conference-2026',
  title: 'Michigan AI Business Conference',
  subtitle: "Exploring AI's Impact Across Finance, Venture Capital, and Business Strategy",
  badgeText: "University of Michigan • AI Business Group Special Event",
  eventDate: 'Friday, October 23, 2026',
  location: 'Stephen M. Ross School of Business, University of Michigan',
  description: "The Michigan AI Business Conference, hosted by the University of Michigan's AI Business Group, is a full-day event bringing together students, faculty, and industry leaders to explore AI's impact across finance, venture capital, and business strategy. Taking place Friday, October 23, 2026 at the Stephen M. Ross School of Business, the conference features keynote speakers, expert panels, coffee chats, and networking opportunities for 300+ attendees. Building on past programming like SXSW 2026 and Fireside Chats with firms such as JP Morgan Chase and Goldman Sachs, the event aims to spark meaningful conversations and connections at the intersection of AI and business.",
  backgroundImageUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?q=80&w=2069&auto=format&fit=crop',
  
  ticketButtonText: 'Buy Tickets',
  ticketButtonUrl: 'https://hailtotheinnovators.splashthat.com/',
  learnMoreButtonText: 'Learn More',
  learnMoreButtonUrl: '#about',
  sponsorButtonText: 'Become a Sponsor',
  sponsorButtonUrl: 'mailto:contact@umichaibusiness.com?subject=Michigan%20AI%20Business%20Conference%20Sponsorship',

  speakersTitle: 'Featured Speakers & Panelists',
  speakersDescription: 'Learn from pioneering executives, venture capitalists, and technologists shaping the future of AI and business.',
  speakers: [
    {
      id: 'speaker-1',
      name: 'Elena Rostova',
      role: 'Managing Director, Applied AI',
      company: 'JP Morgan Chase',
      photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop',
      bio: 'Leads machine learning and generative AI initiatives for institutional client workflows and investment research.',
      linkedinUrl: 'https://linkedin.com',
      order: 1,
    },
    {
      id: 'speaker-2',
      name: 'Marcus Chen',
      role: 'General Partner',
      company: 'Apex Venture Capital',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
      bio: 'Invests in early-stage frontier AI infrastructure and enterprise vertical software companies.',
      linkedinUrl: 'https://linkedin.com',
      order: 2,
    },
    {
      id: 'speaker-3',
      name: 'Dr. Sarah Jenkins',
      role: 'Professor of Business & Tech',
      company: 'Michigan Ross',
      photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800&auto=format&fit=crop',
      bio: 'Renowned researcher on algorithmic market dynamics and organizational adoption of autonomous systems.',
      linkedinUrl: 'https://linkedin.com',
      order: 3,
    },
    {
      id: 'speaker-4',
      name: 'David Sterling',
      role: 'Head of Quantitative Strategies',
      company: 'Goldman Sachs',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
      bio: 'Architecting neural network-driven portfolio optimization and risk evaluation frameworks.',
      linkedinUrl: 'https://linkedin.com',
      order: 4,
    },
    {
      id: 'speaker-5',
      name: 'Aaliyah Patel',
      role: 'VP, Corporate AI Strategy',
      company: 'Global Frontier Tech',
      photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=800&auto=format&fit=crop',
      bio: 'Directs strategic deployment of enterprise reasoning models across Fortune 500 operating groups.',
      linkedinUrl: 'https://linkedin.com',
      order: 5,
    },
  ],

  scheduleTitle: 'Conference Agenda',
  scheduleDescription: 'A dynamic, day-long itinerary designed to ignite discussion, build relationships, and deliver actionable insights.',
  schedule: [
    {
      id: 'sched-1',
      time: '8:30 AM - 9:30 AM',
      title: 'Registration & Morning Coffee Chat',
      location: 'Ross Winter Garden',
      description: 'Check in, receive your attendee badge and conference pack, and connect with fellow attendees over breakfast.',
      order: 1,
    },
    {
      id: 'sched-2',
      time: '9:30 AM - 10:30 AM',
      title: 'Opening Keynote: The Sovereign Era of Enterprise AI',
      location: 'Ross Auditorium',
      description: 'An executive overview of how intelligence architectures are transforming modern business models.',
      order: 2,
    },
    {
      id: 'sched-3',
      time: '10:45 AM - 12:00 PM',
      title: 'Expert Panel: AI in Finance & Quantitative Decision-Making',
      location: 'Robertson Auditorium',
      description: 'Industry leaders from JP Morgan and Goldman Sachs explore algorithmic workflows and predictive underwriting.',
      order: 3,
    },
    {
      id: 'sched-4',
      time: '12:00 PM - 1:30 PM',
      title: 'Networking Lunch & Student-Executive Coffee Chats',
      location: 'Colloquium Hall',
      description: 'Enjoy a catered lunch with dedicated speed-mentoring and table discussions with guest leaders.',
      order: 4,
    },
    {
      id: 'sched-5',
      time: '1:30 PM - 2:45 PM',
      title: 'Venture Capital Panel: Funding the Next Wave of Intelligence',
      location: 'Robertson Auditorium',
      description: 'VC partners discuss where smart capital is flowing across generative agents, robotics, and foundation models.',
      order: 5,
    },
    {
      id: 'sched-6',
      time: '3:00 PM - 4:15 PM',
      title: 'Interactive Case Workshop: Business Strategy in the AI Era',
      location: 'Breakout Suites',
      description: 'Collaborative breakout sessions analyzing real-world deployments and organizational risks.',
      order: 6,
    },
    {
      id: 'sched-7',
      time: '4:30 PM - 5:30 PM',
      title: 'Closing Fireside Chat & Networking Reception',
      location: 'Winter Garden & Terrace',
      description: 'Reflections on the day with special guests, followed by drinks, appetizers, and high-impact networking.',
      order: 7,
    },
  ],

  sponsorsTitle: 'Featured Sponsors & Partners',
  sponsorsDescription: 'Proudly supported by visionary organizations driving technological and commercial progress.',
  sponsors: [
    {
      id: 'sponsor-1',
      name: 'Stephen M. Ross School of Business',
      logoUrl: '/rossLogo.png',
      websiteUrl: 'https://michiganross.umich.edu/',
      tier: 'Title',
      order: 1,
    },
    {
      id: 'sponsor-2',
      name: 'University of Michigan College of Engineering',
      logoUrl: '/engerLogo.png',
      websiteUrl: 'https://engin.umich.edu/',
      tier: 'Platinum',
      order: 2,
    },
    {
      id: 'sponsor-3',
      name: 'AI Business Group Alumni Network',
      logoUrl: '/circleLogo.png',
      websiteUrl: 'https://umichaibusiness.com',
      tier: 'Gold',
      order: 3,
    },
  ],

  isVisible: true,
  updatedAt: Date.now(),
};
